# Generated by Django 4.2.15 on 2024-08-26 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arrienda_ya', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comuna', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_inmueble', models.CharField(verbose_name=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='inmueble',
            name='tipo_inmueble',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefono',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='m2_terreno',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='numero_est',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='tipo',
            field=models.CharField(choices=[('a', 'arrendatario'), ('b', 'arrendador')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='id_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrienda_ya.comuna'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='id_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrienda_ya.region'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='id_tipo_inmueble',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arrienda_ya.tipoinmueble'),
        ),
    ]
